services:
  - type: static
    name: contraste-client
    staticPublishPath: .
    routes:
      - path: /universal-api-client.html
        destination: /universal-api-client.html
      - path: /
        destination: /universal-api-client.html
